# Generated by Django 5.2.1 on 2025-05-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educational_ProgrammModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Стельмак Елизавета Алексеевна', max_length=500, verbose_name='ФИО')),
                ('date_of_birth', models.CharField(default='04.04.04', verbose_name='Дата рождения')),
                ('year', models.IntegerField(default=2022, help_text='Подсказка для значения B', verbose_name='Год поступления')),
                ('courses', models.IntegerField(choices=[(1, 'первый'), (2, 'второй'), (3, 'третий'), (4, 'четвёртый')], default=3, verbose_name='Курс')),
                ('last_year', models.IntegerField(default=2026, max_length=255, verbose_name='Год выпуска')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения(save)')),
            ],
            options={
                'verbose_name': 'Я_и_программа_Таблица',
                'verbose_name_plural': 'Я_и_программа_Таблицы',
                'ordering': ('-pk',),
            },
        ),
    ]
