# Generated by Django 5.2.1 on 2025-05-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StelmakApp", "0002_educational_programmmodel_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educational_programmmodel",
            name="courses",
            field=models.IntegerField(
                choices=[(1, "первый"), (2, "второй"), (3, "третий"), (4, "четвёртый")],
                default=3,
                help_text="от 1 до 4",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="educational_programmmodel",
            name="date_of_birth",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="educational_programmmodel",
            name="result",
            field=models.IntegerField(
                default=4, max_length=255, verbose_name="Сколько осталось учиться"
            ),
        ),
        migrations.AlterField(
            model_name="educational_programmmodel",
            name="year",
            field=models.IntegerField(default=2022, verbose_name="Год поступления"),
        ),
    ]
